#!/bin/bash
echo "Insert number 1"
read number_1
echo "Insert number 2"
read number_2
if [ $number_1 gt $number_2 ]; #gt = greater then
then
echo "$number_1 it's greater then $number_2"
else
echo "$number_2 it's greater then $number_1"
fi
