#!/bin/bash
echo "Insert a number and i will tell you if its negative or positive"
read number
if ["$number" -gt 0] || ["$number" -eq 0] # || means ''or'' #eq means equal
then
echo "The number is positive"
else
echo "The number is negative"
fi
