#!/bin/bash
echo "Enter the hypotenuse of the triangle"
read hypotenuse
echo "Enter the cateto 1 of the triangle"
read cateto_1
echo "Enter the cateto 2 of the triangle"
read cateto_2
perimeter = $((hypotenuse + cateto_1 + cateto_2))
area = $((cateto_1 * cateto_2 / 2))
echo "The perimeter value is $perimetro"
echo "The area value is $area"
