#!/bin/bash
echo "Digite a hipotenusa do triângulo retângulo"
read hipotenusa
echo "Digite o cateto do triângulo retângulo"
read cateto_1
echo "Digite outro cateto do triângulo retângulo"
read cateto_2
perimetro=$((hipotenusa + cateto_1 + cateto_2))
area=$((cateto_1 * cateto_2 / 2))
echo "O perímetro é igual a $perimetro"
echo "A área é igual a $area"
