#!/bin/bash
#Program will inform if the triangle is equilateral, isosceles or scalene
echo "Insert one side of the triangle"
read side_1
echo "Insert another side of the triangle"
read side_2
echo "Insert the last side of the triangle"
read side_3
if [ $side_1 -eq $side_2 ] && [ $side_2 -eq $side_3 ] 
then
echo "The triangle is equilateral"
elif [$side_1 -eq $side_2 ] || [$side_2 -eq $side_3 ]
then
echo "The triangle is isosceles"
else
echo "The triangle is scalene"
fi
